apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: p1
        image: perl
        command:
        - perl
        - -Mbignum=bpi
      restartPolicy: Never
  backoffLimit: 4